"""
Утилиты для взаимодействия с imageFX CLI (Node.js)
"""
import os
import subprocess
import json
import tempfile
import base64
from pathlib import Path
from typing import List, Dict, Any


def get_cookie() -> str:
    """Получает GOOGLE_COOKIE из переменной окружения"""
    cookie = os.getenv("GOOGLE_COOKIE", "")
    if not cookie:
        raise ValueError("GOOGLE_COOKIE environment variable is not set")
    return cookie


def run_imagefx_generate(
    prompt: str,
    model: str = "IMAGEN_3",
    aspect_ratio: str = "IMAGE_ASPECT_RATIO_LANDSCAPE",
    count: int = 1,
    seed: int = 0
) -> List[Dict[str, Any]]:
    """
    Вызывает imageFX CLI для генерации изображений
    
    Возвращает список изображений с base64 данными
    """
    cookie = get_cookie()
    
    # Создаем временную директорию для вывода
    with tempfile.TemporaryDirectory() as temp_dir:
        # Вызываем Node.js CLI
        cmd = [
            "node", "/app/imagefx/dist/cli.js",
            "generate",
            "--prompt", prompt,
            "--model", model,
            "--size", aspect_ratio.replace("IMAGE_ASPECT_RATIO_", ""),  # LANDSCAPE вместо IMAGE_ASPECT_RATIO_LANDSCAPE
            "--count", str(count),
            "--seed", str(seed),
            "--dir", temp_dir,
            "--cookie", cookie
        ]
        
        try:
            result = subprocess.run(
                cmd,
                capture_output=True,
                text=True,
                check=True,
                timeout=120  # 2 минуты таймаут
            )
        except subprocess.CalledProcessError as e:
            raise RuntimeError(f"imageFX CLI failed: {e.stderr}") from e
        except subprocess.TimeoutExpired:
            raise RuntimeError("imageFX CLI timeout (>120s)")
        
        # Читаем сгенерированные изображения
        images = []
        temp_path = Path(temp_dir)
        
        for img_file in sorted(temp_path.glob("image-*.png")):
            # Конвертируем в base64
            with open(img_file, "rb") as f:
                img_data = base64.b64encode(f.read()).decode("utf-8")
                base64_str = f"data:image/png;base64,{img_data}"
            
            # Извлекаем Media ID из вывода CLI (если есть)
            # Для упрощения используем имя файла как временный ID
            media_id = img_file.stem
            
            images.append({
                "media_id": media_id,
                "base64": base64_str,
                "prompt": prompt,
                "model": model,
                "seed": seed,
                "aspect_ratio": aspect_ratio
            })
        
        if not images:
            raise RuntimeError("No images generated by CLI")
        
        return images


def run_imagefx_fetch(media_id: str) -> Dict[str, Any]:
    """
    Получает изображение по Media ID
    
    Возвращает изображение с base64 данными
    """
    cookie = get_cookie()
    
    with tempfile.TemporaryDirectory() as temp_dir:
        cmd = [
            "node", "/app/imagefx/dist/cli.js",
            "fetch",
            media_id,
            "--dir", temp_dir,
            "--cookie", cookie
        ]
        
        try:
            result = subprocess.run(
                cmd,
                capture_output=True,
                text=True,
                check=True,
                timeout=60
            )
        except subprocess.CalledProcessError as e:
            raise RuntimeError(f"imageFX fetch failed: {e.stderr}") from e
        
        # Читаем изображение
        temp_path = Path(temp_dir)
        img_files = list(temp_path.glob("image-*.png"))
        
        if not img_files:
            raise RuntimeError(f"Image with media_id '{media_id}' not found")
        
        img_file = img_files[0]
        with open(img_file, "rb") as f:
            img_data = base64.b64encode(f.read()).decode("utf-8")
            base64_str = f"data:image/png;base64,{img_data}"
        
        return {
            "media_id": media_id,
            "base64": base64_str,
            "prompt": "N/A",  # CLI не возвращает метаданные при fetch
            "model": "N/A",
            "seed": 0,
            "aspect_ratio": "N/A"
        }


def run_imagefx_caption(
    image_base64: str,
    image_type: str = "PNG",
    count: int = 1
) -> List[str]:
    """
    Генерирует описание из изображения
    
    Возвращает список описаний
    """
    cookie = get_cookie()
    
    # Извлекаем чистый base64 (убираем data:image/png;base64, префикс)
    if "base64," in image_base64:
        image_base64 = image_base64.split("base64,")[1]
    
    # Сохраняем во временный файл
    with tempfile.TemporaryDirectory() as temp_dir:
        img_path = Path(temp_dir) / f"input.{image_type.lower()}"
        
        with open(img_path, "wb") as f:
            f.write(base64.b64decode(image_base64))
        
        cmd = [
            "node", "/app/imagefx/dist/cli.js",
            "caption",
            "--image", str(img_path),
            "--type", image_type.upper(),
            "--count", str(count),
            "--cookie", cookie
        ]
        
        try:
            result = subprocess.run(
                cmd,
                capture_output=True,
                text=True,
                check=True,
                timeout=60
            )
        except subprocess.CalledProcessError as e:
            raise RuntimeError(f"imageFX caption failed: {e.stderr}") from e
        
        # Парсим вывод CLI для получения captions
        # CLI выводит каptions построчно в stdout
        captions = [line.strip() for line in result.stdout.split("\n") if line.strip()]
        
        if not captions:
            raise RuntimeError("No captions generated")
        
        return captions[:count]  # Ограничиваем количество
